"""empty message

Revision ID: fc05a7fad53f
Revises: 
Create Date: 2023-05-24 11:31:21.698722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc05a7fad53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('oeis_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('oeis_offset', sa.Integer(), nullable=False),
    sa.Column('vals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('values_requested', sa.Boolean(), nullable=False),
    sa.Column('raw_refs', sa.String(), nullable=True),
    sa.Column('backrefs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata_requested', sa.Boolean(), nullable=False),
    sa.Column('factors', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('oeis_id'),
    sa.UniqueConstraint('oeis_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequences')
    # ### end Alembic commands ###
