#!/bin/bash

# --- classify requirements ---

not_installed=()
not_required=()
indirectly_required=()
directly_required=()

for dep in $(cat requirements-freeze.txt); do
  pkg=${dep%==*}
  details=$(pip show $pkg 2> /dev/null)
  if [ -z "$details" ]; then
    not_installed+=( $pkg )
  else
    # hat tip Anton Korneychuk (https://stackoverflow.com/a/69022922)
    if grep -q "^$pkg\s*\(#\|$\)" requirements.txt; then
      # explicitly required
      directly_required+=( $pkg )
    else
      # not explicitly required
      parents_line=$(echo "$details" | grep Required-by)
      parents=${parents_line#"Required-by: "}
      if [ "$parents" ]; then
        # required by another package
        indirectly_required+=( "$pkg ← $parents" )
      else
        # not required by another package
        not_required+=( $pkg )
      fi
    fi
  fi
done

# --- list requirements ---

tput setaf 1; echo -n ╭──; tput bold; echo " Not installed ────────"
for pkg in "${not_installed[@]}"; do
  echo -n │
  tput sgr0; echo " $pkg"; tput setaf 1
done
echo ╰─────────────────────────

tput setaf 3; echo -n ╭──; tput bold; echo " Not required ─────────"
for pkg in "${not_required[@]}"; do
  echo -n │
  tput sgr0; echo " $pkg"; tput setaf 3
done
echo ╰─────────────────────────

tput setaf 2; echo -n ╭──; tput bold; echo " Indirectly required ──"
for pkg in "${indirectly_required[@]}"; do
  echo -n │
  tput sgr0; echo " $pkg"; tput setaf 2
done
echo ╰─────────────────────────

tput setaf 4; echo -n ╭──; tput bold; echo " Directly required ────"
for pkg in "${directly_required[@]}"; do
  echo -n │
  tput sgr0; echo " $pkg"; tput setaf 4
done
echo ╰─────────────────────────

# reset terminal style to default
tput sgr0