name: Continuous integration
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install (most) dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Attempt to install cypari2
        continue-on-error: true
        run: |
          sudo apt install pari-gp
          source .venv/bin/activate
          pip install cysignals
          pip install Cython
          pip install cypari2
      - name: Test backscope
        run: |
          source .venv/bin/activate
          pytest