name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install (most) dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Install cypari2 (first round)
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pip install --force cypari2
      - name: Install cypari2 (second round)
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pip install --force cypari2
      - name: Test backscope
        run: |
          source .venv/bin/activate
          pytest